(import (rnrs io ports))

(define p (open-file-input/output-port "out.txt" (file-options no-fail no-truncate) 'line (make-transcoder (latin-1-codec))))
;(define outp (transcoded-port p (utf-8-codec)))
;(printf "outp? ~a\n" (output-port? p))
(format p "Hello, World!~%~!")
(flush-output-port p)
(set-port-position! p 0)
(define x (get-char p))
;(printf "Read from file: ~a\n" x)
(format #t "~a~%" x)