name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: debian-trixie
    env:
      MMTK_GC_TRIGGER: DynamicHeapSize:1G,8G
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: https://codeberg.org/wackbyte/rust-toolchain@trunk
        with:
          toolchain: nightly

      - name: Install system deps
        shell: bash
        run: |
          set -euo pipefail
          apt update -y
          apt install -y clang gcc rsync make

      - name: Run tests
        shell: bash
        run: |
          set -euo pipefail
          make test
