name: nightly 
on:
  schedule:
    - cron: '@daily'
  workflow_dispatch:
jobs:
  check-and-run:
    runs-on: fedora-latest 
    outputs:
      recent_commits: ${{ steps.check_commits.outputs.recent_commits }}
      date: ${{ steps.check_commits.outputs.date }}
      short_sha: ${{ steps.check_commits.outputs.short_sha }}
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Check recent commits 
        id: check_commits
        run: |
          # git log command returns commits since "24 hours ago"
          # We check if the output is empty
          echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          if [ -n "$(git log --since='24 hours ago')" ]; then
            echo "recent_commits=true" >> $GITHUB_OUTPUT
            echo "Found recent commits."
          else
            echo "recent_commits=false" >> $GITHUB_OUTPUT
            echo "No recent commits found. Skipping job."
          fi
  build: 
    needs: check-and-run
    if: needs.check-and-run.outputs.recent_commits == 'true'
    name: Build nightly (${{ matrix.arch }})
    strategy:
      matrix:
        arch: [x86_64]

    runs-on: fedora-latest
    env:
      VERSION: nightly-${{ needs.check-and-run.outputs.date }}-${{ needs.check-and-run.outputs.short_sha }}
      MMTK_GC_TRIGGER: DynamicHeapSize:1G,4G
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: https://codeberg.org/wackbyte/rust-toolchain@trunk
        with: 
          toolchain: nightly
      - name: Install system deps
        shell: bash
        run: |
          apt update -y
          apt install -y clang lld rsync make

      - name: Build Capy
        shell: bash
        run: |
          make build
      - name: Create portable tarball
        shell: bash
        run: |
          make dist-portable
          