#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Intrinsic {
    S8Eq,
    S8Gt,
    S8Lt,
    S8Ge,
    S8Le,
    S8Add,
    S8Sub,
    S8Mul,
    S8Div,
    S8Rem,
    S8Shl,
    S8Shr,
    S8And,
    S8Or,
    S8Xor,
    S8ToS16,
    S8ToS32,
    S8ToS64,
    S16Eq,
    S16Gt,
    S16Lt,
    S16Ge,
    S16Le,
    S16Add,
    S16Sub,
    S16Mul,
    S16Div,
    S16Rem,
    S16Shl,
    S16Shr,
    S16And,
    S16Or,
    S16Xor,
    S16ToS8,
    S16ToS32,
    S16ToS64,
    S32Eq,
    S32Gt,
    S32Lt,
    S32Ge,
    S32Le,
    S32Add,
    S32Sub,
    S32Mul,
    S32Div,
    S32Rem,
    S32Shl,
    S32Shr,
    S32And,
    S32Or,
    S32Xor,
    S32ToS8,
    S32ToS16,
    S32ToS64,
    S32ToU64,
    S64Eq,
    S64Gt,
    S64Lt,
    S64Ge,
    S64Le,
    S64Add,
    S64Sub,
    S64Mul,
    S64Div,
    S64Rem,
    S64Shl,
    S64Shr,
    S64And,
    S64Or,
    S64Xor,
    S64ToS8,
    S64ToS16,
    S64ToS32,
    U8Eq,
    U8Gt,
    U8Lt,
    U8Ge,
    U8Le,
    U8Add,
    U8Sub,
    U8Mul,
    U8Div,
    U8Rem,
    U8Shl,
    U8Shr,
    U8And,
    U8Or,
    U8Xor,
    U8ToU16,
    U8ToU32,
    U8ToU64,
    U16Eq,
    U16Gt,
    U16Lt,
    U16Ge,
    U16Le,
    U16Add,
    U16Sub,
    U16Mul,
    U16Div,
    U16Rem,
    U16Shl,
    U16Shr,
    U16And,
    U16Or,
    U16Xor,
    U16ToU8,
    U16ToU32,
    U16ToU64,
    U32Eq,
    U32Gt,
    U32Lt,
    U32Ge,
    U32Le,
    U32Add,
    U32Sub,
    U32Mul,
    U32Div,
    U32Rem,
    U32Shl,
    U32Shr,
    U32And,
    U32Or,
    U32Xor,
    U32ToU8,
    U32ToU16,
    U32ToU64,
    U64Eq,
    U64Gt,
    U64Lt,
    U64Ge,
    U64Le,
    U64Add,
    U64Sub,
    U64Mul,
    U64Div,
    U64Rem,
    U64Shl,
    U64Shr,
    U64And,
    U64Or,
    U64Xor,
    U64ToU8,
    U64ToU16,
    U64ToU32,
    S64ToU64,
    S64ToU32,
    S64ToU16,
    Typecode8,
    Typecode16,
    Typecode8Eq,
    Typecode16Eq,
    Refptr,
    Ref8,
    Ref16,
    Ref32,
    Ref64,
    Store8,
    Store16,
    Store32,
    Store64,
    UsizeToValue,
    CacheRef,
    CacheSet,
    IsImmediate,
    IsHeapObject,
    VariableBound,
    VariableRef,
    VariableSet,
    MakeBox,
    EnsureLocalVar,
    Lookup,
    LookupBound,
    LookupBoundPublic,
    LookupBoundPrivate,
    CurrentModule,
    SetCurrentModule,
    Define,
    Not,
    IsProcedure,
    IsVariable,
    SetCar,
    SetCdr,
    Cons,
    Reverse,
    IsEofObject,
    IsNull,
    Unspec,
    IsUnspecified,
    IsPair,
    IsList,
    Append,
    List,
    IsVector,
    IsBytevector,
    Vector,
    Tuple,
    MakeTuple,
    MakeVector,
    VectorRef,
    VectorSet,
    IsString,
    IsBoolean,
    IsSymbol,
    IsEq,
    IsEqv,
    IsEqual,
    IsFixnum,
    UntagFixnum,
    IsExactInteger,
    IsInteger,
    IsChar,
    IsNumber,
    IsComplex,
    IsNan,
    Ash,
    Logand,
    Logior,
    Lognot,
    IntegerToChar,
    CharToInteger,
    Expt,
    Abs,
    Sqrt,
    Cos,
    Sin,
    Tan,
    Atan,
    Asin,
    Acos,
    Ceiling,
    Floor,
    Truncate,
    Plus,
    Minus,
    Times,
    Div,
    NumericEqual,
    NumericLt,
    NumericGt,
    NumericGte,
    NumericLte,
    Memq,
    Memv,
    ExactToInexact,
    InexactToExact,
    IsReal,
    IsRational,
    IsInexact,
    IsExact,
    IsEven,
    IsOdd,
    IsZero,
    Car,
    Cdr,
    Breakpoint,
    TupleSize,
    TupleRef,
    TupleSet,
    IsTuple,
    SymbolToString,
    StringToSymbol,
    StringLength,
    StringRef,
    StringSet,
    Length,
    Quotient,
    Remainder,
    Modulo,
    PushCframe,
    CurrentContinuationMarks,
    SetAttachments,
    Winders,
    MakeSyntax,
    DefaultRetk,

    _Count,
}

impl Intrinsic {
    pub fn is_effect_free(&self) -> bool {
        matches!(
            self,
            Intrinsic::Cons
                | Intrinsic::List
                | Intrinsic::Vector
                | Intrinsic::MakeVector
                | Intrinsic::Tuple
                | Intrinsic::MakeTuple
                | Intrinsic::CacheRef
                | Intrinsic::Typecode8
                | Intrinsic::Typecode16
                | Intrinsic::U8Eq
                | Intrinsic::Typecode8Eq
                | Intrinsic::IsImmediate
                | Intrinsic::IsHeapObject
                | Intrinsic::UntagFixnum
                | Intrinsic::IsFixnum
                | Intrinsic::UsizeToValue
                | Intrinsic::IsBoolean
                | Intrinsic::VariableBound
                | Intrinsic::VariableRef
                | Intrinsic::CurrentModule
                | Intrinsic::IsBytevector
                | Intrinsic::IsVector
                | Intrinsic::IsVariable
                | Intrinsic::IsChar
                | Intrinsic::IsEq
                | Intrinsic::IsEqv
                | Intrinsic::IsEqual
                | Intrinsic::IsList
                | Intrinsic::IsNull
                | Intrinsic::IsPair
                | Intrinsic::IsString
                | Intrinsic::IsSymbol
        )
    }
}
