(library (core unicode)
    (export
        char-upcase
        char-downcase
        char-titlecase
        char-foldcase
        char-ci=?
        char-ci<?
        char-ci>?
        char-ci<=?
        char-ci>=?
        char-alphabetic?
        char-numeric?
        char-whitespace?
        char-upper-case?
        char-lower-case?
        char-title-case?
        char-general-category
        string-upcase
        string-downcase
        string-foldcase
        string-titlecase
        string-ci=?
        string-ci<?
        string-ci>?
        string-ci<=?
        string-ci>=?
        string-normalize-nfc
        string-normalize-nfd
        string-normalize-nfkc
        string-normalize-nfkd)
    (import (capy)))