[package]
name = "capy-derive"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.108", features = ["full", "visit-mut"] }
proc-macro2 = "1.0.103"
quote = "1.0.41"


[lib]
proc-macro = true
