(import (capy))

(define-class point ()
  ((x :accessor point-x)
   y
   (label #:init-value 'point)
   (origin :initform 'generated)
   (notes #:init-value '())
   (kind :allocation :class #:init-value 'cartesian)))

(define-class colored-point (point) (color))

(define-class reflected-point ()
  ((visible
     #:slot-ref (lambda (self) (list 'visible (slot-ref self 'backing)))
     #:slot-set! (lambda (self value) (slot-set! self 'backing value))
     #:slot-bound? (lambda (self) (slot-bound? self 'backing)))
   (backing #:initializable #f)))

(define-class callable-point ()
  (procedure label)
  :applicable #t)

(define p
  (make point #:x 3 #:y 4))

(define cp
  (make-instance colored-point #:x 5 #:y 6 #:color 'red))

(define reflected
  (make-instance reflected-point))

(define callable
  (make-instance callable-point
    #:procedure (lambda (self value) (list (slot-ref self 'label) value))
    #:label 'callable))

(define-class alternate-point ()
  ((x #:init-value 0)
   changed))

(define changeable
  (make point #:x 1 #:y 2))

(define-generic describe-point)
(define-generic scale-point)
(define-generic sealed-point)
(define-generic describe-any
  :fallback (lambda (obj) (list 'fallback obj)))
(define-generic sealed-from-definition :sealed #t)

(define-method (describe-point (obj point)) :locked
  (list 'point (slot-ref obj 'x) (slot-ref obj 'y)))

(define-method (describe-point (obj colored-point))
  (list 'colored
        (slot-ref obj 'color)
        (next-method)))

(define-method (scale-point (obj point) #:optional (label 'scaled) #:key (factor 1))
  (list label
        (* (slot-ref obj 'x) factor)
        (* (slot-ref obj 'y) factor)))

(define-method (sealed-point (obj point))
  (list 'sealed (slot-ref obj 'x)))

(display (describe-point p))
(newline)
(display (class-name <class>))
(newline)
(display (generic? slot-unbound))
(newline)
(display (generic? class-post-initialize))
(newline)
(display (generic? describe))
(newline)
(display (class-name <string>))
(newline)
(display (class-name <bytevector>))
(newline)
(display (class-name <hash-table>))
(newline)
(display (class-name <box>))
(newline)
(display (class-name <module>))
(newline)
(display (class-name <thread>))
(newline)
(display (class-name <generic>))
(newline)
(display (x->string 'symbolic))
(newline)
(display (x->number "37"))
(newline)
(display (x->integer #\A))
(newline)
(display (ref p 'x))
(newline)
((setter ref) p 'x 8)
(display (ref p 'x))
(newline)
(display (ref (vector 'left 'right) 1))
(newline)
(define sample-bytes (make-bytevector 2 7))
((setter ref) sample-bytes 1 9)
(display (ref sample-bytes 1))
(newline)
(define sample-table (make-core-hashtable 'eq?))
((setter ref) sample-table 'answer 42)
(display (ref sample-table 'answer))
(newline)
(define sample-box (box 'inside))
((setter ref) sample-box '* 'changed)
(display (ref sample-box 0))
(newline)
(display (~ (vector (list 'left (vector 'deep 'value))) 0 1 1))
(newline)
(display
  (not
    (not
      (string-contains
        (with-output-to-string
          (lambda ()
            (describe p)))
        "slots:"))))
(newline)
(display (describe-point cp))
(newline)
(display (apply-generic describe-point (list cp)))
(newline)
(display (next-method-option (generic-next-methods describe-point cp) ':has-next?))
(newline)
(display (next-method? (generic-next-methods describe-point cp)))
(newline)
(display (is-a? cp point))
(newline)
(display (subclass? colored-point point))
(newline)
(display (method-applicable-for-classes? (car (generic-methods describe-point)) colored-point))
(newline)
(display (scale-point p))
(newline)
(display (scale-point cp 'triple #:factor 3))
(newline)
(display (describe-any 'loose))
(newline)
(display (generic-sealed? sealed-from-definition))
(newline)
(change-class changeable alternate-point)
(display (class-name (class-of changeable)))
(newline)
(display (slot-ref changeable 'x))
(newline)
(generic-seal! sealed-point)
(display (generic-sealed? sealed-point))
(newline)
(generic-unseal! sealed-point)
(display (generic-sealed? sealed-point))
(newline)
(display (slot-ref p 'label))
(newline)
(display (slot-ref p 'origin))
(newline)
(display (class-slot-ref point 'kind))
(newline)
(class-slot-set! point 'kind 'polar)
(display (slot-ref p 'kind))
(newline)
(display ((setter point-x) p 10))
(newline)
(display (point-x p))
(newline)
(instance-slot-set! p 1 12)
(display (instance-slot-ref p 1))
(newline)
(slot-initialize-using-accessor! p (class-slot-accessor point 'x) (list #:x 13))
(display (point-x p))
(newline)
(display (slot-ref-using-class point p 'x))
(newline)
(slot-set-using-class! point p 'x 15)
(display (slot-ref-using-class point p 'x))
(newline)
(display (slot-bound-using-class? point p 'x))
(newline)
(display (slot-exists? p 'notes))
(newline)
(display (slot-exists-using-class? point p 'notes))
(newline)
(slot-push! p 'notes 'warm)
(slot-push! p 'notes 'bright)
(display (slot-pop! p 'notes))
(newline)
(display (slot-ref p 'notes))
(newline)
(display (slot-bound? reflected 'visible))
(newline)
(slot-set! reflected 'visible 'custom)
(display (slot-ref reflected 'visible))
(newline)
(display (slot-ref-using-accessor reflected (class-slot-accessor reflected-point 'visible)))
(newline)
(display (slot-definition-name (class-slot-definition colored-point 'x)))
(newline)
(display (slot-definition-allocation (class-slot-definition point 'label)))
(newline)
(display (slot-definition-option (class-slot-definition point 'label) #:init-value))
(newline)
(display (slot-definition-accessor (class-slot-definition point 'x)))
(newline)
(display (slot-accessor-option (class-slot-accessor point 'x) ':accessor))
(newline)
(display (class-option colored-point ':name))
(newline)
(display (generic-option sealed-from-definition ':sealed))
(newline)
(display (generic-required-dispatch-arg-count describe-point))
(newline)
(display (method-option (car (generic-methods describe-point)) #:locked))
(newline)
(display (has-setter? class-slot-ref))
(newline)
(display (map slot-definition-name (class-slots colored-point)))
(newline)
(display (map slot-accessor-name (class-accessors colored-point)))
(newline)
(display (callable 99))
(newline)
(display (class-applicable? callable-point))
(newline)
