use bytecodegen::Operand;
use capy_derive::Trace;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Trace, Serialize, Deserialize, Operand)]
#[repr(u16)]
pub enum Primitive {
    S8Eq,
    S8Gt,
    S8Lt,
    S8Ge,
    S8Le,
    S8Add,
    S8Sub,
    S8Mul,
    S8Div,
    S8Rem,
    S8Shl,
    S8Shr,
    S8And,
    S8Or,
    S8Xor,
    S8ToS16,
    S8ToS32,
    S8ToS64,
    S16Eq,
    S16Gt,
    S16Lt,
    S16Ge,
    S16Le,
    S16Add,
    S16Sub,
    S16Mul,
    S16Div,
    S16Rem,
    S16Shl,
    S16Shr,
    S16And,
    S16Or,
    S16Xor,
    S16ToS8,
    S16ToS32,
    S16ToS64,
    S32Eq,
    S32Gt,
    S32Lt,
    S32Ge,
    S32Le,
    S32Add,
    S32Sub,
    S32Mul,
    S32Div,
    S32Rem,
    S32Shl,
    S32Shr,
    S32And,
    S32Or,
    S32Xor,
    S32ToS8,
    S32ToS16,
    S32ToS64,
    S32ToU64,
    S64Eq,
    S64Gt,
    S64Lt,
    S64Ge,
    S64Le,
    S64Add,
    S64Sub,
    S64Mul,
    S64Div,
    S64Rem,
    S64Shl,
    S64Shr,
    S64And,
    S64Or,
    S64Xor,
    S64ToS8,
    S64ToS16,
    S64ToS32,
    U8Eq,
    U8Gt,
    U8Lt,
    U8Ge,
    U8Le,
    U8Add,
    U8Sub,
    U8Mul,
    U8Div,
    U8Rem,
    U8Shl,
    U8Shr,
    U8And,
    U8Or,
    U8Xor,
    U8ToU16,
    U8ToU32,
    U8ToU64,
    U16Eq,
    U16Gt,
    U16Lt,
    U16Ge,
    U16Le,
    U16Add,
    U16Sub,
    U16Mul,
    U16Div,
    U16Rem,
    U16Shl,
    U16Shr,
    U16And,
    U16Or,
    U16Xor,
    U16ToU8,
    U16ToU32,
    U16ToU64,
    U32Eq,
    U32Gt,
    U32Lt,
    U32Ge,
    U32Le,
    U32Add,
    U32Sub,
    U32Mul,
    U32Div,
    U32Rem,
    U32Shl,
    U32Shr,
    U32And,
    U32Or,
    U32Xor,
    U32ToU8,
    U32ToU16,
    U32ToU64,
    U64Eq,
    U64Gt,
    U64Lt,
    U64Ge,
    U64Le,
    U64Add,
    U64Sub,
    U64Mul,
    U64Div,
    U64Rem,
    U64Shl,
    U64Shr,
    U64And,
    U64Or,
    U64Xor,
    U64ToU8,
    U64ToU16,
    U64ToU32,
    S64ToU64,
    S64ToU32,
    S64ToU16,
    Typecode8,
    Refptr,
    Ref8,
    Ref16,
    Ref32,
    Ref64,
    Store8,
    Store16,
    Store32,
    Store64,
    UsizeToValue,
    CacheRef,
    CacheSet,
    IsImmediate,
    IsHeapObject,
    VariableBound,
    VariableRef,
    VariableSet,
    MakeBox,
    EnsureLocalVar,
    Lookup,
    LookupBound,
    LookupBoundPublic,
    LookupBoundPrivate,
    CurrentModule,
    Define,
    Not,
    IsProcedure,
    IsVariable,
    SetCar,
    SetCdr,
    Cons,
    Reverse,
    IsEofObject,
    IsNull,
    Unspec,
    IsUnspecified,
    IsPair,
    IsList,
    Append,
    List,
    IsVector,
    IsBytevector,
    Vector,
    Tuple,
    MakeTuple,
    MakeVector,
    VectorRef,
    VectorSet,
    IsString,
    StringLength,
    IsBoolean,
    IsSymbol,
    IsEq,
    IsEqv,
    IsEqual,
    IsFixnum,
    UntagFixnum,
    IsExactInteger,
    IsInteger,
    IsChar,
    IsNumber,
    IsComplex,
    IsNan,
    Ash,
    Logand,
    Logior,
    Lognot,
    IntegerToChar,
    CharToInteger,
    Expt,
    Abs,
    Sqrt,
    Cos,
    Sin,
    Tan,
    Atan,
    Asin,
    Acos,
    Ceiling,
    Floor,
    Truncate,
    Plus,
    Minus,
    Times,
    Div,
    NumericEqual,
    NumericLt,
    NumericGt,
    NumericGte,
    NumericLte,
    Memq,
    Memv,
    ExactToInexact,
    InexactToExact,
    IsReal,
    IsRational,
    IsInexact,
    IsExact,
    IsEven,
    IsOdd,
    IsZero,
    Car,
    Cdr,
    Breakpoint,
    TupleSize,
    TupleRef,
    TupleSet,
    IsTuple,
    SymbolToString,
    StringToSymbol,
    Length,
    Quotient,
    Remainder,
    Modulo,
    PushCframe,
    CurrentContinuationMarks,
    SetAttachments,
    Winders,
    MakeSyntax,
    DefaultRetk,
}

impl Primitive {
    pub fn name(&self) -> &'static str {
        match self {
            Primitive::S8Eq => "s8=",
            Primitive::S8Gt => "s8>",
            Primitive::S8Lt => "s8<",
            Primitive::S8Ge => "s8>=",
            Primitive::S8Le => "s8<=",
            Primitive::S8Add => "s8+",
            Primitive::S8Sub => "s8-",
            Primitive::S8Mul => "s8*",
            Primitive::S8Div => "s8/",
            Primitive::S8Rem => "s8%",
            Primitive::S8Shl => "s8<<",
            Primitive::S8Shr => "s8>>",
            Primitive::S8And => "s8&",
            Primitive::S8Or => "s8|",
            Primitive::S8Xor => "s8^",
            Primitive::S8ToS16 => "s8->s16",
            Primitive::S8ToS32 => "s8->s32",
            Primitive::S8ToS64 => "s8->s64",
            Primitive::S16Eq => "s16=",
            Primitive::S16Gt => "s16>",
            Primitive::S16Lt => "s16<",
            Primitive::S16Ge => "s16>=",
            Primitive::S16Le => "s16<=",
            Primitive::S16Add => "s16+",
            Primitive::S16Sub => "s16-",
            Primitive::S16Mul => "s16*",
            Primitive::S16Div => "s16/",
            Primitive::S16Rem => "s16%",
            Primitive::S16Shl => "s16<<",
            Primitive::S16Shr => "s16>>",
            Primitive::S16And => "s16&",
            Primitive::S16Or => "s16|",
            Primitive::S16Xor => "s16^",
            Primitive::S16ToS8 => "s16->s8",
            Primitive::S16ToS32 => "s16->s32",
            Primitive::S16ToS64 => "s16->s64",
            Primitive::S32Eq => "s32=",
            Primitive::S32Gt => "s32>",
            Primitive::S32Lt => "s32<",
            Primitive::S32Ge => "s32>=",
            Primitive::S32Le => "s32<=",
            Primitive::S32Add => "s32+",
            Primitive::S32Sub => "s32-",
            Primitive::S32Mul => "s32*",
            Primitive::S32Div => "s32/",
            Primitive::S32Rem => "s32%",
            Primitive::S32Shl => "s32<<",
            Primitive::S32Shr => "s32>>",
            Primitive::S32And => "s32&",
            Primitive::S32Or => "s32|",
            Primitive::S32Xor => "s32^",
            Primitive::S32ToS8 => "s32->s8",
            Primitive::S32ToS16 => "s32->s16",
            Primitive::S32ToS64 => "s32->s64",
            Primitive::S32ToU64 => "s32->u64",
            Primitive::S64Eq => "s64=",
            Primitive::S64Gt => "s64>",
            Primitive::S64Lt => "s64<",
            Primitive::S64Ge => "s64>=",
            Primitive::S64Le => "s64<=",
            Primitive::S64Add => "s64+",
            Primitive::S64Sub => "s64-",
            Primitive::S64Mul => "s64*",
            Primitive::S64Div => "s64/",
            Primitive::S64Rem => "s64%",
            Primitive::S64Shl => "s64<<",
            Primitive::S64Shr => "s64>>",
            Primitive::S64And => "s64&",
            Primitive::S64Or => "s64|",
            Primitive::S64Xor => "s64^",
            Primitive::S64ToS8 => "s64->s8",
            Primitive::S64ToS16 => "s64->s16",
            Primitive::S64ToS32 => "s64->s32",
            Primitive::U8Eq => "u8=",
            Primitive::U8Gt => "u8>",
            Primitive::U8Lt => "u8<",
            Primitive::U8Ge => "u8>=",
            Primitive::U8Le => "u8<=",
            Primitive::U8Add => "u8+",
            Primitive::U8Sub => "u8-",
            Primitive::U8Mul => "u8*",
            Primitive::U8Div => "u8/",
            Primitive::U8Rem => "u8%",
            Primitive::U8Shl => "u8<<",
            Primitive::U8Shr => "u8>>",
            Primitive::U8And => "u8&",
            Primitive::U8Or => "u8|",
            Primitive::U8Xor => "u8^",
            Primitive::U8ToU16 => "u8->u16",
            Primitive::U8ToU32 => "u8->u32",
            Primitive::U8ToU64 => "u8->u64",
            Primitive::U16Eq => "u16=",
            Primitive::U16Gt => "u16>",
            Primitive::U16Lt => "u16<",
            Primitive::U16Ge => "u16>=",
            Primitive::U16Le => "u16<=",
            Primitive::U16Add => "u16+",
            Primitive::U16Sub => "u16-",
            Primitive::U16Mul => "u16*",
            Primitive::U16Div => "u16/",
            Primitive::U16Rem => "u16%",
            Primitive::U16Shl => "u16<<",
            Primitive::U16Shr => "u16>>",
            Primitive::U16And => "u16&",
            Primitive::U16Or => "u16|",
            Primitive::U16Xor => "u16^",
            Primitive::U16ToU8 => "u16->u8",
            Primitive::U16ToU32 => "u16->u32",
            Primitive::U16ToU64 => "u16->u64",
            Primitive::U32Eq => "u32=",
            Primitive::U32Gt => "u32>",
            Primitive::U32Lt => "u32<",
            Primitive::U32Ge => "u32>=",
            Primitive::U32Le => "u32<=",
            Primitive::U32Add => "u32+",
            Primitive::U32Sub => "u32-",
            Primitive::U32Mul => "u32*",
            Primitive::U32Div => "u32/",
            Primitive::U32Rem => "u32%",
            Primitive::U32Shl => "u32<<",
            Primitive::U32Shr => "u32>>",
            Primitive::U32And => "u32&",
            Primitive::U32Or => "u32|",
            Primitive::U32Xor => "u32^",
            Primitive::U32ToU8 => "u32->u8",
            Primitive::U32ToU16 => "u32->u16",
            Primitive::U32ToU64 => "u32->u64",
            Primitive::U64Eq => "u64=",
            Primitive::U64Gt => "u64>",
            Primitive::U64Lt => "u64<",
            Primitive::U64Ge => "u64>=",
            Primitive::U64Le => "u64<=",
            Primitive::U64Add => "u64+",
            Primitive::U64Sub => "u64-",
            Primitive::U64Mul => "u64*",
            Primitive::U64Div => "u64/",
            Primitive::U64Rem => "u64%",
            Primitive::U64Shl => "u64<<",
            Primitive::U64Shr => "u64>>",
            Primitive::U64And => "u64&",
            Primitive::U64Or => "u64|",
            Primitive::U64Xor => "u64^",
            Primitive::U64ToU8 => "u64->u8",
            Primitive::U64ToU16 => "u64->u16",
            Primitive::U64ToU32 => "u64->u32",
            Primitive::S64ToU64 => "s64->u64",
            Primitive::S64ToU32 => "s64->u32",
            Primitive::S64ToU16 => "s64->u16",
            Primitive::Typecode8 => "%typecode8",
            Primitive::Refptr => "%refptr",
            Primitive::Ref8 => "%ref8",
            Primitive::Ref16 => "%ref16",
            Primitive::Ref32 => "%ref32",
            Primitive::Ref64 => "%ref64",
            Primitive::Store8 => "%store8",
            Primitive::Store16 => "%store16",
            Primitive::Store32 => "%store32",
            Primitive::Store64 => "%store64",
            Primitive::UsizeToValue => "usize->value",
            Primitive::CacheRef => "cache-ref",
            Primitive::CacheSet => "cache-set!",
            Primitive::IsImmediate => "immediate?",
            Primitive::IsHeapObject => "heap-object?",
            Primitive::VariableBound => "variable-bound?",
            Primitive::VariableRef => "variable-ref",
            Primitive::VariableSet => "variable-set!",
            Primitive::MakeBox => "make-variable",
            Primitive::EnsureLocalVar => "module-ensure-local-variable!",
            Primitive::Lookup => "lookup",
            Primitive::LookupBound => "lookup-bound",
            Primitive::LookupBoundPublic => "lookup-bound-public",
            Primitive::LookupBoundPrivate => "lookup-bound-private",
            Primitive::CurrentModule => "current-module",
            Primitive::Define => "define",
            Primitive::Not => "not",
            Primitive::IsProcedure => "procedure?",
            Primitive::IsVariable => "variable?",
            Primitive::SetCar => "set-car!",
            Primitive::SetCdr => "set-cdr!",
            Primitive::Cons => "cons",
            Primitive::Reverse => "reverse",
            Primitive::IsEofObject => "eof-object?",
            Primitive::IsNull => "null?",
            Primitive::Unspec => "unspecified",
            Primitive::IsUnspecified => "unspecified?",
            Primitive::IsPair => "pair?",
            Primitive::IsList => "list?",
            Primitive::Append => "append",
            Primitive::List => "list",
            Primitive::IsVector => "vector?",
            Primitive::IsBytevector => "bytevector?",
            Primitive::Vector => "vector",
            Primitive::Tuple => "tuple",
            Primitive::MakeTuple => "make-tuple",
            Primitive::MakeVector => "make-vector",
            Primitive::VectorRef => "vector-ref",
            Primitive::VectorSet => "vector-set!",
            Primitive::IsString => "string?",
            Primitive::StringLength => "string-length",
            Primitive::IsBoolean => "boolean?",
            Primitive::IsSymbol => "symbol?",
            Primitive::IsEq => "eq?",
            Primitive::IsEqv => "eqv?",
            Primitive::IsEqual => "equal?",
            Primitive::IsFixnum => "fixnum?",
            Primitive::UntagFixnum => "untag-fixnum",
            Primitive::IsExactInteger => "exact-integer?",
            Primitive::IsInteger => "integer?",
            Primitive::IsChar => "char?",
            Primitive::IsNumber => "number?",
            Primitive::IsComplex => "complex?",
            Primitive::IsNan => "nan?",
            Primitive::Ash => "ash",
            Primitive::Logand => "logand",
            Primitive::Logior => "logior",
            Primitive::Lognot => "lognot",
            Primitive::IntegerToChar => "integer->char",
            Primitive::CharToInteger => "char->integer",
            Primitive::Expt => "expt",
            Primitive::Abs => "abs",
            Primitive::Sqrt => "sqrt",
            Primitive::Cos => "cos",
            Primitive::Sin => "sin",
            Primitive::Tan => "tan",
            Primitive::Atan => "atan",
            Primitive::Asin => "asin",
            Primitive::Acos => "acos",
            Primitive::Ceiling => "ceiling",
            Primitive::Floor => "floor",
            Primitive::Truncate => "truncate",
            Primitive::Plus => "+",
            Primitive::Minus => "-",
            Primitive::Times => "*",
            Primitive::Div => "/",
            Primitive::NumericEqual => "=",
            Primitive::NumericLt => "<",
            Primitive::NumericGt => ">",
            Primitive::NumericGte => ">=",
            Primitive::NumericLte => "<=",
            Primitive::Memq => "memq",
            Primitive::Memv => "memv",
            Primitive::ExactToInexact => "exact->inexact",
            Primitive::InexactToExact => "inexact->exact",
            Primitive::IsReal => "real?",
            Primitive::IsRational => "rational?",
            Primitive::IsInexact => "inexact?",
            Primitive::IsExact => "exact?",
            Primitive::IsEven => "even?",
            Primitive::IsOdd => "odd?",
            Primitive::IsZero => "zero?",
            Primitive::Car => "car",
            Primitive::Cdr => "cdr",
            Primitive::Breakpoint => ".breakpoint",
            Primitive::TupleSize => "tuple-size",
            Primitive::TupleRef => "tuple-ref",
            Primitive::TupleSet => "tuple-set!",
            Primitive::IsTuple => "tuple?",
            Primitive::SymbolToString => "symbol->string",
            Primitive::StringToSymbol => "string->symbol",
            Primitive::Length => "length",
            Primitive::Quotient => "quotient",
            Primitive::Remainder => "remainder",
            Primitive::Modulo => "modulo",
            Primitive::PushCframe => "push-cframe",
            Primitive::CurrentContinuationMarks => "current-continuation-marks",
            Primitive::SetAttachments => "$set-attachments!",
            Primitive::Winders => "$winders",
            Primitive::MakeSyntax => "make-syntax",
            Primitive::DefaultRetk => "#%default-retk",
        }
    }

    pub fn from_name(name: &str) -> Option<Primitive> {
        match name {
            "s8=" => Some(Primitive::S8Eq),
            "s8>" => Some(Primitive::S8Gt),
            "s8<" => Some(Primitive::S8Lt),
            "s8>=" => Some(Primitive::S8Ge),
            "s8<=" => Some(Primitive::S8Le),
            "s8+" => Some(Primitive::S8Add),
            "s8-" => Some(Primitive::S8Sub),
            "s8*" => Some(Primitive::S8Mul),
            "s8/" => Some(Primitive::S8Div),
            "s8%" => Some(Primitive::S8Rem),
            "s8<<" => Some(Primitive::S8Shl),
            "s8>>" => Some(Primitive::S8Shr),
            "s8&" => Some(Primitive::S8And),
            "s8|" => Some(Primitive::S8Or),
            "s8^" => Some(Primitive::S8Xor),
            "s8->s16" => Some(Primitive::S8ToS16),
            "s8->s32" => Some(Primitive::S8ToS32),
            "s8->s64" => Some(Primitive::S8ToS64),
            "s16=" => Some(Primitive::S16Eq),
            "s16>" => Some(Primitive::S16Gt),
            "s16<" => Some(Primitive::S16Lt),
            "s16>=" => Some(Primitive::S16Ge),
            "s16<=" => Some(Primitive::S16Le),
            "s16+" => Some(Primitive::S16Add),
            "s16-" => Some(Primitive::S16Sub),
            "s16*" => Some(Primitive::S16Mul),
            "s16/" => Some(Primitive::S16Div),
            "s16%" => Some(Primitive::S16Rem),
            "s16<<" => Some(Primitive::S16Shl),
            "s16>>" => Some(Primitive::S16Shr),
            "s16&" => Some(Primitive::S16And),
            "s16|" => Some(Primitive::S16Or),
            "s16^" => Some(Primitive::S16Xor),
            "s16->s8" => Some(Primitive::S16ToS8),
            "s16->s32" => Some(Primitive::S16ToS32),
            "s16->s64" => Some(Primitive::S16ToS64),
            "s32=" => Some(Primitive::S32Eq),
            "s32>" => Some(Primitive::S32Gt),
            "s32<" => Some(Primitive::S32Lt),
            "s32>=" => Some(Primitive::S32Ge),
            "s32<=" => Some(Primitive::S32Le),
            "s32+" => Some(Primitive::S32Add),
            "s32-" => Some(Primitive::S32Sub),
            "s32*" => Some(Primitive::S32Mul),
            "s32/" => Some(Primitive::S32Div),
            "s32%" => Some(Primitive::S32Rem),
            "s32<<" => Some(Primitive::S32Shl),
            "s32>>" => Some(Primitive::S32Shr),
            "s32&" => Some(Primitive::S32And),
            "s32|" => Some(Primitive::S32Or),
            "s32^" => Some(Primitive::S32Xor),
            "s32->s8" => Some(Primitive::S32ToS8),
            "s32->s16" => Some(Primitive::S32ToS16),
            "s32->s64" => Some(Primitive::S32ToS64),
            "s32->u64" => Some(Primitive::S32ToU64),
            "s64=" => Some(Primitive::S64Eq),
            "s64>" => Some(Primitive::S64Gt),
            "s64<" => Some(Primitive::S64Lt),
            "s64>=" => Some(Primitive::S64Ge),
            "s64<=" => Some(Primitive::S64Le),
            "s64+" => Some(Primitive::S64Add),
            "s64-" => Some(Primitive::S64Sub),
            "s64*" => Some(Primitive::S64Mul),
            "s64/" => Some(Primitive::S64Div),
            "s64%" => Some(Primitive::S64Rem),
            "s64<<" => Some(Primitive::S64Shl),
            "s64>>" => Some(Primitive::S64Shr),
            "s64&" => Some(Primitive::S64And),
            "s64|" => Some(Primitive::S64Or),
            "s64^" => Some(Primitive::S64Xor),
            "s64->s8" => Some(Primitive::S64ToS8),
            "s64->s16" => Some(Primitive::S64ToS16),
            "s64->s32" => Some(Primitive::S64ToS32),
            "u8=" => Some(Primitive::U8Eq),
            "u8>" => Some(Primitive::U8Gt),
            "u8<" => Some(Primitive::U8Lt),
            "u8>=" => Some(Primitive::U8Ge),
            "u8<=" => Some(Primitive::U8Le),
            "u8+" => Some(Primitive::U8Add),
            "u8-" => Some(Primitive::U8Sub),
            "u8*" => Some(Primitive::U8Mul),
            "u8/" => Some(Primitive::U8Div),
            "u8%" => Some(Primitive::U8Rem),
            "u8<<" => Some(Primitive::U8Shl),
            "u8>>" => Some(Primitive::U8Shr),
            "u8&" => Some(Primitive::U8And),
            "u8|" => Some(Primitive::U8Or),
            "u8^" => Some(Primitive::U8Xor),
            "u8->u16" => Some(Primitive::U8ToU16),
            "u8->u32" => Some(Primitive::U8ToU32),
            "u8->u64" => Some(Primitive::U8ToU64),
            "u16=" => Some(Primitive::U16Eq),
            "u16>" => Some(Primitive::U16Gt),
            "u16<" => Some(Primitive::U16Lt),
            "u16>=" => Some(Primitive::U16Ge),
            "u16<=" => Some(Primitive::U16Le),
            "u16+" => Some(Primitive::U16Add),
            "u16-" => Some(Primitive::U16Sub),
            "u16*" => Some(Primitive::U16Mul),
            "u16/" => Some(Primitive::U16Div),
            "u16%" => Some(Primitive::U16Rem),
            "u16<<" => Some(Primitive::U16Shl),
            "u16>>" => Some(Primitive::U16Shr),
            "u16&" => Some(Primitive::U16And),
            "u16|" => Some(Primitive::U16Or),
            "u16^" => Some(Primitive::U16Xor),
            "u16->u8" => Some(Primitive::U16ToU8),
            "u16->u32" => Some(Primitive::U16ToU32),
            "u16->u64" => Some(Primitive::U16ToU64),
            "u32=" => Some(Primitive::U32Eq),
            "u32>" => Some(Primitive::U32Gt),
            "u32<" => Some(Primitive::U32Lt),
            "u32>=" => Some(Primitive::U32Ge),
            "u32<=" => Some(Primitive::U32Le),
            "u32+" => Some(Primitive::U32Add),
            "u32-" => Some(Primitive::U32Sub),
            "u32*" => Some(Primitive::U32Mul),
            "u32/" => Some(Primitive::U32Div),
            "u32%" => Some(Primitive::U32Rem),
            "u32<<" => Some(Primitive::U32Shl),
            "u32>>" => Some(Primitive::U32Shr),
            "u32&" => Some(Primitive::U32And),
            "u32|" => Some(Primitive::U32Or),
            "u32^" => Some(Primitive::U32Xor),
            "u32->u8" => Some(Primitive::U32ToU8),
            "u32->u16" => Some(Primitive::U32ToU16),
            "u32->u64" => Some(Primitive::U32ToU64),
            "u64=" => Some(Primitive::U64Eq),
            "u64>" => Some(Primitive::U64Gt),
            "u64<" => Some(Primitive::U64Lt),
            "u64>=" => Some(Primitive::U64Ge),
            "u64<=" => Some(Primitive::U64Le),
            "u64+" => Some(Primitive::U64Add),
            "u64-" => Some(Primitive::U64Sub),
            "u64*" => Some(Primitive::U64Mul),
            "u64/" => Some(Primitive::U64Div),
            "u64%" => Some(Primitive::U64Rem),
            "u64<<" => Some(Primitive::U64Shl),
            "u64>>" => Some(Primitive::U64Shr),
            "u64&" => Some(Primitive::U64And),
            "u64|" => Some(Primitive::U64Or),
            "u64^" => Some(Primitive::U64Xor),
            "u64->u8" => Some(Primitive::U64ToU8),
            "u64->u16" => Some(Primitive::U64ToU16),
            "u64->u32" => Some(Primitive::U64ToU32),
            "s64->u64" => Some(Primitive::S64ToU64),
            "s64->u32" => Some(Primitive::S64ToU32),
            "s64->u16" => Some(Primitive::S64ToU16),
            "%typecode8" => Some(Primitive::Typecode8),
            "%refptr" => Some(Primitive::Refptr),
            "%ref8" => Some(Primitive::Ref8),
            "%ref16" => Some(Primitive::Ref16),
            "%ref32" => Some(Primitive::Ref32),
            "%ref64" => Some(Primitive::Ref64),
            "%store8" => Some(Primitive::Store8),
            "%store16" => Some(Primitive::Store16),
            "%store32" => Some(Primitive::Store32),
            "%store64" => Some(Primitive::Store64),
            "usize->value" => Some(Primitive::UsizeToValue),
            "cache-ref" => Some(Primitive::CacheRef),
            "cache-set!" => Some(Primitive::CacheSet),
            "immediate?" => Some(Primitive::IsImmediate),
            "heap-object?" => Some(Primitive::IsHeapObject),
            "variable-bound?" => Some(Primitive::VariableBound),
            "variable-ref" => Some(Primitive::VariableRef),
            "variable-set!" => Some(Primitive::VariableSet),
            "make-variable" => Some(Primitive::MakeBox),
            "module-ensure-local-variable!" => Some(Primitive::EnsureLocalVar),
            "lookup" => Some(Primitive::Lookup),
            "lookup-bound" => Some(Primitive::LookupBound),
            "lookup-bound-public" => Some(Primitive::LookupBoundPublic),
            "lookup-bound-private" => Some(Primitive::LookupBoundPrivate),
            "current-module" => Some(Primitive::CurrentModule),
            "define" => Some(Primitive::Define),
            "not" => Some(Primitive::Not),
            "procedure?" => Some(Primitive::IsProcedure),
            "variable?" => Some(Primitive::IsVariable),
            "set-car!" => Some(Primitive::SetCar),
            "set-cdr!" => Some(Primitive::SetCdr),
            "cons" => Some(Primitive::Cons),
            "reverse" => Some(Primitive::Reverse),
            "eof-object?" => Some(Primitive::IsEofObject),
            "null?" => Some(Primitive::IsNull),
            "unspecified" => Some(Primitive::Unspec),
            "unspecified?" => Some(Primitive::IsUnspecified),
            "pair?" => Some(Primitive::IsPair),
            "list?" => Some(Primitive::IsList),
            "append" => Some(Primitive::Append),
            "list" => Some(Primitive::List),
            "vector?" => Some(Primitive::IsVector),
            "bytevector?" => Some(Primitive::IsBytevector),
            "vector" => Some(Primitive::Vector),
            "tuple" => Some(Primitive::Tuple),
            "make-tuple" => Some(Primitive::MakeTuple),
            "make-vector" => Some(Primitive::MakeVector),
            "vector-ref" => Some(Primitive::VectorRef),
            "vector-set!" => Some(Primitive::VectorSet),
            "string?" => Some(Primitive::IsString),
            "string-length" => Some(Primitive::StringLength),
            "boolean?" => Some(Primitive::IsBoolean),
            "symbol?" => Some(Primitive::IsSymbol),
            "eq?" => Some(Primitive::IsEq),
            "eqv?" => Some(Primitive::IsEqv),
            "equal?" => Some(Primitive::IsEqual),
            "fixnum?" => Some(Primitive::IsFixnum),
            "untag-fixnum" => Some(Primitive::UntagFixnum),
            "exact-integer?" => Some(Primitive::IsExactInteger),
            "integer?" => Some(Primitive::IsInteger),
            "char?" => Some(Primitive::IsChar),
            "number?" => Some(Primitive::IsNumber),
            "complex?" => Some(Primitive::IsComplex),
            "nan?" => Some(Primitive::IsNan),
            "ash" => Some(Primitive::Ash),
            "logand" => Some(Primitive::Logand),
            "logior" => Some(Primitive::Logior),
            "lognot" => Some(Primitive::Lognot),
            "integer->char" => Some(Primitive::IntegerToChar),
            "char->integer" => Some(Primitive::CharToInteger),
            "expt" => Some(Primitive::Expt),
            "abs" => Some(Primitive::Abs),
            "sqrt" => Some(Primitive::Sqrt),
            "cos" => Some(Primitive::Cos),
            "sin" => Some(Primitive::Sin),
            "tan" => Some(Primitive::Tan),
            "atan" => Some(Primitive::Atan),
            "asin" => Some(Primitive::Asin),
            "acos" => Some(Primitive::Acos),
            "ceiling" => Some(Primitive::Ceiling),
            "floor" => Some(Primitive::Floor),
            "truncate" => Some(Primitive::Truncate),
            "+" => Some(Primitive::Plus),
            "-" => Some(Primitive::Minus),
            "*" => Some(Primitive::Times),
            "/" => Some(Primitive::Div),
            "=" => Some(Primitive::NumericEqual),
            "<" => Some(Primitive::NumericLt),
            ">" => Some(Primitive::NumericGt),
            ">=" => Some(Primitive::NumericGte),
            "<=" => Some(Primitive::NumericLte),
            "memq" => Some(Primitive::Memq),
            "memv" => Some(Primitive::Memv),
            "exact->inexact" => Some(Primitive::ExactToInexact),
            "inexact->exact" => Some(Primitive::InexactToExact),
            "real?" => Some(Primitive::IsReal),
            "rational?" => Some(Primitive::IsRational),
            "inexact?" => Some(Primitive::IsInexact),
            "exact?" => Some(Primitive::IsExact),
            "even?" => Some(Primitive::IsEven),
            "odd?" => Some(Primitive::IsOdd),
            "zero?" => Some(Primitive::IsZero),
            "car" => Some(Primitive::Car),
            "cdr" => Some(Primitive::Cdr),
            ".breakpoint" => Some(Primitive::Breakpoint),
            "tuple-size" => Some(Primitive::TupleSize),
            "tuple-ref" => Some(Primitive::TupleRef),
            "tuple-set!" => Some(Primitive::TupleSet),
            "tuple?" => Some(Primitive::IsTuple),
            "symbol->string" => Some(Primitive::SymbolToString),
            "string->symbol" => Some(Primitive::StringToSymbol),
            "length" => Some(Primitive::Length),
            "quotient" => Some(Primitive::Quotient),
            "remainder" => Some(Primitive::Remainder),
            "modulo" => Some(Primitive::Modulo),
            "push-cframe" => Some(Primitive::PushCframe),
            "current-continuation-marks" => Some(Primitive::CurrentContinuationMarks),
            "$set-attachments!" => Some(Primitive::SetAttachments),
            "$winders" => Some(Primitive::Winders),
            "make-syntax" => Some(Primitive::MakeSyntax),
            "#%default-retk" => Some(Primitive::DefaultRetk),
            _ => None,
        }
    }
}
