(library (capy keywords)
    (export (rename (new-lambda lambda))
            (rename (new-app |#%app|))
            (rename (new-define define)))
    (import (capy keywords impl)
            (core control)))